version: '3.7'
services:
    web:
        image: odoo:12.0
        depends_on:
            - mydb
        ports:
            - "8079:8069"
        env_file:
            - odoo.env
        restart: always
        volumes: 
            - ./custom_modules:/mnt/extra-addons
            - ./config:/etc/odoo
            - web-data:/var/lib/odoo
        networks:
            - my-network
    mydb:
        image: postgres:10
        env_file:
            - postgres.env
        networks:
            - my-network
        restart: always
        volumes: 
            - db-data:/var/lib/postgresql/data/pgdata
    adminer:
        image: adminer
        restart: always
        depends_on: 
            - mydb
        networks:
            - my-network
        ports:
        - 8080:8080
networks:
    my-network:
        driver: bridge
volumes:
    db-data:
    web-data:

        
        
        



    

        
